---
abstract: 'clone and checkout a Git repository'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Carp: '0'
  Cwd: '0'
  Dist::Zilla::Role::Plugin: '0'
  Exporter: '0'
  File::Path: '2.07'
  File::Spec::Functions: '0'
  Test::DZil: '0'
  Test::Fatal: '0'
  Test::MockModule: '0.14'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Git-Checkout
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  Dist::Zilla::Role::BeforeRelease: '0'
  Git::Background: '0.002'
  Git::Version::Compare: '0'
  Moose: '0'
  MooseX::Types::Moose: '0'
  Path::Tiny: '0'
  Term::ANSIColor: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Dist-Zilla-Plugin-Git-Checkout/issues
  homepage: https://github.com/skirmess/Dist-Zilla-Plugin-Git-Checkout
  repository: https://github.com/skirmess/Dist-Zilla-Plugin-Git-Checkout.git
version: '0.003'
x_spdx_expression: BSD-2-Clause-FreeBSD
