name: test

on:
  push:
  pull_request:
  schedule:
    - cron:  '5 7 11 * *'

jobs:
  strawberry2:
    runs-on: windows-latest

    env:
      TAR_OPTIONS: --warning=no-unknown-keyword

    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.32.1
          distribution: strawberry

      - name: install cpanm
        run: |
          Invoke-WebRequest https://cpanmin.us/ -OutFile cpanm.pl
          perl cpanm.pl --reinstall App::cpanminus
          erase cpanm.pl

      - name: installsitebin
        run: |
          $installsitebin = perl -MConfig -e 'print $Config{installsitebin};'
          echo "installsitebin = $installsitebin"
          echo "::set-output name=path::$installsitebin"
        id: installsitebin

      - name: cpanm --installdeps --notest .
        run: |
          mv cpanfile .cpanfile.disabled
          perl ${{ steps.installsitebin.outputs.path }}\cpanm --verbose --installdeps --notest .
          mv .cpanfile.disabled cpanfile
        working-directory: ${{ github.event.repository.name }}
        env:
          AUTOMATED_TESTING: 1

      - name: perl Makefile.PL
        run: perl Makefile.PL
        working-directory: ${{ github.event.repository.name }}
        env:
          AUTOMATED_TESTING: 1
          PERL_USE_UNSAFE_INC: 0

      - name: make
        run: make
        working-directory: ${{ github.event.repository.name }}
        env:
          PERL_USE_UNSAFE_INC: 0

      - name: prove -vl t
        run: prove -vl t/basic4.t
        working-directory: ${{ github.event.repository.name }}
        env:
          AUTOMATED_TESTING: 1
          PERL_USE_UNSAFE_INC: 0
